pub mod action_builder;
pub mod app;
pub mod app_identity;
pub mod app_version;
pub mod arg_key;
pub mod argument;
pub mod argument_parser;
pub mod error;
pub mod parsed_arg;
pub mod terminal;

pub use action_builder::{ActionBuilder, ActionProvider};
pub use app::App;
pub use app_identity::AppIdentity;
pub use app_version::AppVersion;
pub use terminal::Color;
pub use terminal::TerminalNode;
pub use terminal::TerminalNodes;
pub use terminal::TextEffect;
pub use terminal::TextFormat;
